<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="38" total="48" passed="10">
  <reporter-output>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Pass: Address2 is not require]]>
    </line>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Require field message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Require field message doesn't show]]>
    </line>
    <line>
      <![CDATA[Pass: No wrong confirm password error message show]]>
    </line>
    <line>
      <![CDATA[Pass: No wrong email format error message show]]>
    </line>
    <line>
      <![CDATA[Pass: No password format error message show]]>
    </line>
    <line>
      <![CDATA[Pass: No wrong phone format error message show]]>
    </line>
    <line>
      <![CDATA[Pass: Correct default value]]>
    </line>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Require field message doesn't show]]>
    </line>
    <line>
      <![CDATA[Pass: Max length data can submit to system]]>
    </line>
    <line>
      <![CDATA[Pass: No error message show]]>
    </line>
    <line>
      <![CDATA[Pass: No error message show]]>
    </line>
    <line>
      <![CDATA[Fail: Require field message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Require field message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Min length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Require field message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Require field message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Require field message doesn't show]]>
    </line>
    <line>
      <![CDATA[Pass: Special character can submit to system]]>
    </line>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Require field message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Max length error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Require field message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong confirm password error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong confirm password error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong confirm password error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong email format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong email format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong email format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong email format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong email format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong email format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong email format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong email format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong email format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong password format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong password format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong password format error message doesn't show]]>
    </line>
    <line>
      <![CDATA[Fail: Wrong phone format error message doesn't show]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="455117" started-at="2016-12-18T15:11:12Z" finished-at="2016-12-18T15:18:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="455117" started-at="2016-12-18T15:11:12Z" finished-at="2016-12-18T15:18:47Z">
      <class name="Register.RegisterTest">
        <test-method status="FAIL" signature="Address2ExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="Address2ExceedMaxlength" duration-ms="10417" started-at="2016-12-18T22:11:12Z" finished-at="2016-12-18T22:11:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.Address2ExceedMaxlength(RegisterTest.java:453)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- Address2ExceedMaxlength -->
        <test-method status="PASS" signature="Address2Require()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="Address2Require" duration-ms="10446" started-at="2016-12-18T22:11:23Z" finished-at="2016-12-18T22:11:33Z">
          <reporter-output>
            <line>
              <![CDATA[Pass: Address2 is not require]]>
            </line>
          </reporter-output>
        </test-method> <!-- Address2Require -->
        <test-method status="FAIL" signature="AddressExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="AddressExceedMaxlength" duration-ms="10104" started-at="2016-12-18T22:11:33Z" finished-at="2016-12-18T22:11:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.AddressExceedMaxlength(RegisterTest.java:437)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- AddressExceedMaxlength -->
        <test-method status="FAIL" signature="AddressRequire()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="AddressRequire" duration-ms="10261" started-at="2016-12-18T22:11:43Z" finished-at="2016-12-18T22:11:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Require field message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Require field message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.AddressRequire(RegisterTest.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Require field message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- AddressRequire -->
        <test-method status="FAIL" signature="CityExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="CityExceedMaxlength" duration-ms="9073" started-at="2016-12-18T22:11:54Z" finished-at="2016-12-18T22:12:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.CityExceedMaxlength(RegisterTest.java:469)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- CityExceedMaxlength -->
        <test-method status="FAIL" signature="CityRequire()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="CityRequire" duration-ms="10002" started-at="2016-12-18T22:12:03Z" finished-at="2016-12-18T22:12:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Require field message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Require field message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.CityRequire(RegisterTest.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Require field message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- CityRequire -->
        <test-method status="PASS" signature="CorrectConfirmPassword()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="CorrectConfirmPassword" duration-ms="9255" started-at="2016-12-18T22:12:13Z" finished-at="2016-12-18T22:12:22Z">
          <reporter-output>
            <line>
              <![CDATA[Pass: No wrong confirm password error message show]]>
            </line>
          </reporter-output>
        </test-method> <!-- CorrectConfirmPassword -->
        <test-method status="PASS" signature="CorrectEmailFormat()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="CorrectEmailFormat" duration-ms="9046" started-at="2016-12-18T22:12:22Z" finished-at="2016-12-18T22:12:31Z">
          <reporter-output>
            <line>
              <![CDATA[Pass: No wrong email format error message show]]>
            </line>
          </reporter-output>
        </test-method> <!-- CorrectEmailFormat -->
        <test-method status="PASS" signature="CorrectPasswordFormat()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="CorrectPasswordFormat" duration-ms="9476" started-at="2016-12-18T22:12:31Z" finished-at="2016-12-18T22:12:40Z">
          <reporter-output>
            <line>
              <![CDATA[Pass: No password format error message show]]>
            </line>
          </reporter-output>
        </test-method> <!-- CorrectPasswordFormat -->
        <test-method status="PASS" signature="CorrectPhoneFormat()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="CorrectPhoneFormat" duration-ms="9116" started-at="2016-12-18T22:12:40Z" finished-at="2016-12-18T22:12:50Z">
          <reporter-output>
            <line>
              <![CDATA[Pass: No wrong phone format error message show]]>
            </line>
          </reporter-output>
        </test-method> <!-- CorrectPhoneFormat -->
        <test-method status="PASS" signature="CountryDefaultValue()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="CountryDefaultValue" duration-ms="7850" started-at="2016-12-18T22:12:50Z" finished-at="2016-12-18T22:12:57Z">
          <reporter-output>
            <line>
              <![CDATA[Pass: Correct default value]]>
            </line>
          </reporter-output>
        </test-method> <!-- CountryDefaultValue -->
        <test-method status="FAIL" signature="EmailExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="EmailExceedMaxlength" duration-ms="8729" started-at="2016-12-18T22:12:57Z" finished-at="2016-12-18T22:13:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.EmailExceedMaxlength(RegisterTest.java:421)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- EmailExceedMaxlength -->
        <test-method status="FAIL" signature="EmailRequire()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="EmailRequire" duration-ms="10185" started-at="2016-12-18T22:13:06Z" finished-at="2016-12-18T22:13:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Require field message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Require field message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.EmailRequire(RegisterTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Require field message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- EmailRequire -->
        <test-method status="PASS" signature="FieldMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="FieldMaxlength" duration-ms="10170" started-at="2016-12-18T22:13:16Z" finished-at="2016-12-18T22:13:27Z">
          <reporter-output>
            <line>
              <![CDATA[Pass: Max length data can submit to system]]>
            </line>
          </reporter-output>
        </test-method> <!-- FieldMaxlength -->
        <test-method status="PASS" signature="FieldMiddlelength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="FieldMiddlelength" duration-ms="9313" started-at="2016-12-18T22:13:27Z" finished-at="2016-12-18T22:13:36Z">
          <reporter-output>
            <line>
              <![CDATA[Pass: No error message show]]>
            </line>
          </reporter-output>
        </test-method> <!-- FieldMiddlelength -->
        <test-method status="PASS" signature="FieldMinlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="FieldMinlength" duration-ms="9017" started-at="2016-12-18T22:13:36Z" finished-at="2016-12-18T22:13:45Z">
          <reporter-output>
            <line>
              <![CDATA[Pass: No error message show]]>
            </line>
          </reporter-output>
        </test-method> <!-- FieldMinlength -->
        <test-method status="FAIL" signature="FirstNameRequire()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="FirstNameRequire" duration-ms="9887" started-at="2016-12-18T22:13:45Z" finished-at="2016-12-18T22:13:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Require field message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Require field message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.FirstNameRequire(RegisterTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Require field message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- FirstNameRequire -->
        <test-method status="FAIL" signature="FirstnameExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="FirstnameExceedMaxlength" duration-ms="8879" started-at="2016-12-18T22:13:55Z" finished-at="2016-12-18T22:14:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.FirstnameExceedMaxlength(RegisterTest.java:373)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- FirstnameExceedMaxlength -->
        <test-method status="FAIL" signature="LastNameRequire()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="LastNameRequire" duration-ms="10015" started-at="2016-12-18T22:14:04Z" finished-at="2016-12-18T22:14:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Require field message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Require field message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.LastNameRequire(RegisterTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Require field message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- LastNameRequire -->
        <test-method status="FAIL" signature="LastnameExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="LastnameExceedMaxlength" duration-ms="9018" started-at="2016-12-18T22:14:14Z" finished-at="2016-12-18T22:14:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.LastnameExceedMaxlength(RegisterTest.java:389)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- LastnameExceedMaxlength -->
        <test-method status="FAIL" signature="PasswordExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="PasswordExceedMaxlength" duration-ms="8891" started-at="2016-12-18T22:14:23Z" finished-at="2016-12-18T22:14:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.PasswordExceedMaxlength(RegisterTest.java:533)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- PasswordExceedMaxlength -->
        <test-method status="FAIL" signature="PasswordLowerThanMinlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="PasswordLowerThanMinlength" duration-ms="9030" started-at="2016-12-18T22:14:32Z" finished-at="2016-12-18T22:14:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Min length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Min length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.PasswordLowerThanMinlength(RegisterTest.java:549)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Min length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- PasswordLowerThanMinlength -->
        <test-method status="FAIL" signature="PasswordRequire()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="PasswordRequire" duration-ms="10097" started-at="2016-12-18T22:14:41Z" finished-at="2016-12-18T22:14:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Require field message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Require field message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.PasswordRequire(RegisterTest.java:343)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Require field message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- PasswordRequire -->
        <test-method status="FAIL" signature="PhoneExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="PhoneExceedMaxlength" duration-ms="8742" started-at="2016-12-18T22:14:51Z" finished-at="2016-12-18T22:14:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.PhoneExceedMaxlength(RegisterTest.java:405)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- PhoneExceedMaxlength -->
        <test-method status="FAIL" signature="PhoneRequire()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="PhoneRequire" duration-ms="10062" started-at="2016-12-18T22:14:59Z" finished-at="2016-12-18T22:15:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Require field message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Require field message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.PhoneRequire(RegisterTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Require field message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- PhoneRequire -->
        <test-method status="FAIL" signature="PostalCodeExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="PostalCodeExceedMaxlength" duration-ms="9057" started-at="2016-12-18T22:15:10Z" finished-at="2016-12-18T22:15:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.PostalCodeExceedMaxlength(RegisterTest.java:501)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- PostalCodeExceedMaxlength -->
        <test-method status="FAIL" signature="PostalCodeRequire()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="PostalCodeRequire" duration-ms="10409" started-at="2016-12-18T22:15:19Z" finished-at="2016-12-18T22:15:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Require field message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Require field message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.PostalCodeRequire(RegisterTest.java:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Require field message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- PostalCodeRequire -->
        <test-method status="PASS" signature="SpecialCharacterInput()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="SpecialCharacterInput" duration-ms="13089" started-at="2016-12-18T22:15:29Z" finished-at="2016-12-18T22:15:42Z">
          <reporter-output>
            <line>
              <![CDATA[Pass: Special character can submit to system]]>
            </line>
          </reporter-output>
        </test-method> <!-- SpecialCharacterInput -->
        <test-method status="FAIL" signature="StateExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="StateExceedMaxlength" duration-ms="9193" started-at="2016-12-18T22:15:42Z" finished-at="2016-12-18T22:15:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.StateExceedMaxlength(RegisterTest.java:485)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- StateExceedMaxlength -->
        <test-method status="FAIL" signature="StateRequire()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="StateRequire" duration-ms="10051" started-at="2016-12-18T22:15:51Z" finished-at="2016-12-18T22:16:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Require field message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Require field message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.StateRequire(RegisterTest.java:254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Require field message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- StateRequire -->
        <test-method status="FAIL" signature="UsernameExceedMaxlength()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="UsernameExceedMaxlength" duration-ms="8976" started-at="2016-12-18T22:16:01Z" finished-at="2016-12-18T22:16:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Max length error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.UsernameExceedMaxlength(RegisterTest.java:517)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Max length error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- UsernameExceedMaxlength -->
        <test-method status="FAIL" signature="UsernameRequire()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="UsernameRequire" duration-ms="10285" started-at="2016-12-18T22:16:10Z" finished-at="2016-12-18T22:16:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Require field message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Require field message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.UsernameRequire(RegisterTest.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Require field message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- UsernameRequire -->
        <test-method status="FAIL" signature="WrongConfirmPassword1()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongConfirmPassword1" duration-ms="9194" started-at="2016-12-18T22:16:21Z" finished-at="2016-12-18T22:16:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong confirm password error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong confirm password error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongConfirmPassword1(RegisterTest.java:881)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong confirm password error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongConfirmPassword1 -->
        <test-method status="FAIL" signature="WrongConfirmPassword2()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongConfirmPassword2" duration-ms="9468" started-at="2016-12-18T22:16:30Z" finished-at="2016-12-18T22:16:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong confirm password error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong confirm password error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongConfirmPassword2(RegisterTest.java:898)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong confirm password error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongConfirmPassword2 -->
        <test-method status="FAIL" signature="WrongConfirmPassword3()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongConfirmPassword3" duration-ms="9060" started-at="2016-12-18T22:16:39Z" finished-at="2016-12-18T22:16:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong confirm password error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong confirm password error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongConfirmPassword3(RegisterTest.java:915)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong confirm password error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongConfirmPassword3 -->
        <test-method status="FAIL" signature="WrongEmailFormat1()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongEmailFormat1" duration-ms="8869" started-at="2016-12-18T22:16:48Z" finished-at="2016-12-18T22:16:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong email format error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongEmailFormat1(RegisterTest.java:656)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongEmailFormat1 -->
        <test-method status="FAIL" signature="WrongEmailFormat2()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongEmailFormat2" duration-ms="8987" started-at="2016-12-18T22:16:57Z" finished-at="2016-12-18T22:17:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong email format error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongEmailFormat2(RegisterTest.java:672)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongEmailFormat2 -->
        <test-method status="FAIL" signature="WrongEmailFormat3()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongEmailFormat3" duration-ms="10291" started-at="2016-12-18T22:17:06Z" finished-at="2016-12-18T22:17:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong email format error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongEmailFormat3(RegisterTest.java:688)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongEmailFormat3 -->
        <test-method status="FAIL" signature="WrongEmailFormat4()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongEmailFormat4" duration-ms="9096" started-at="2016-12-18T22:17:16Z" finished-at="2016-12-18T22:17:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong email format error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongEmailFormat4(RegisterTest.java:704)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongEmailFormat4 -->
        <test-method status="FAIL" signature="WrongEmailFormat5()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongEmailFormat5" duration-ms="9257" started-at="2016-12-18T22:17:26Z" finished-at="2016-12-18T22:17:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong email format error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongEmailFormat5(RegisterTest.java:720)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongEmailFormat5 -->
        <test-method status="FAIL" signature="WrongEmailFormat6()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongEmailFormat6" duration-ms="9127" started-at="2016-12-18T22:17:35Z" finished-at="2016-12-18T22:17:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong email format error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongEmailFormat6(RegisterTest.java:736)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongEmailFormat6 -->
        <test-method status="FAIL" signature="WrongEmailFormat7()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongEmailFormat7" duration-ms="9182" started-at="2016-12-18T22:17:44Z" finished-at="2016-12-18T22:17:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong email format error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongEmailFormat7(RegisterTest.java:752)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongEmailFormat7 -->
        <test-method status="FAIL" signature="WrongEmailFormat8()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongEmailFormat8" duration-ms="9223" started-at="2016-12-18T22:17:53Z" finished-at="2016-12-18T22:18:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong email format error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongEmailFormat8(RegisterTest.java:768)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongEmailFormat8 -->
        <test-method status="FAIL" signature="WrongEmailFormat9()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongEmailFormat9" duration-ms="9208" started-at="2016-12-18T22:18:02Z" finished-at="2016-12-18T22:18:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong email format error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongEmailFormat9(RegisterTest.java:784)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong email format error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!-- WrongEmailFormat9 -->
        <test-method status="FAIL" signature="WrongPasswordFormat1()[pri:0, instance:Register.RegisterTest@3bfdc050]" name="WrongPasswordFormat1" duration-ms="8853" started-at="2016-12-18T22:18:12Z" finished-at="2016-12-18T22:18:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail: Wrong password format error message doesn't show]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail: Wrong password format error message doesn't show
	at org.testng.Assert.fail(Assert.java:94)
	at Register.RegisterTest.WrongPasswordFormat1(RegisterTest.java:816)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Fail: Wrong password format error message doesn't show]]>
            </line>
          </reporter-output>
        </test-method> <!